-- SQL RPG bootstrap for Supabase Postgres
-- Run in Supabase SQL Editor.

create table if not exists public.challenges (
  id bigint generated by default as identity primary key,
  prompt text not null,
  difficulty text not null check (difficulty in ('easy', 'medium', 'hard')),
  hint text,
  expected_signature text not null
);

create table if not exists public.goblins (
  id bigint generated by default as identity primary key,
  name text not null,
  hp integer not null check (hp > 0),
  dungeon text not null
);

create table if not exists public.player_progress (
  user_id uuid primary key references auth.users(id) on delete cascade,
  level integer not null default 1,
  xp integer not null default 0,
  gold integer not null default 0,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  challenge_id bigint not null references public.challenges(id) on delete cascade,
  sql_text text not null,
  success boolean not null,
  feedback text not null,
  damage integer not null default 0,
  critical boolean not null default false,
  xp_awarded integer not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

create or replace function public.execute_arena_sql(query_text text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  payload jsonb;
begin
  if query_text is null or btrim(query_text) = '' then
    raise exception 'Query bos olamaz';
  end if;

  if query_text ~ ';' then
    raise exception 'Noktali virgul yasak';
  end if;

  if query_text !~* '^\s*select\b' then
    raise exception 'Sadece SELECT sorgusu kabul edilir';
  end if;

  if query_text ~* '\m(insert|update|delete|drop|alter|create|grant|revoke|truncate)\M' then
    raise exception 'Yazma veya DDL komutlari yasak';
  end if;

  perform set_config('statement_timeout', '3000', true);

  execute format('select coalesce(jsonb_agg(row_to_json(t)), ''[]''::jsonb) from (%s) t', query_text)
  into payload;

  return coalesce(payload, '[]'::jsonb);
end;
$$;

revoke all on function public.execute_arena_sql(text) from public;
grant execute on function public.execute_arena_sql(text) to anon, authenticated;

alter table public.player_progress enable row level security;
alter table public.attempts enable row level security;

drop policy if exists "progress_select_own" on public.player_progress;
create policy "progress_select_own"
on public.player_progress for select
using (auth.uid() = user_id);

drop policy if exists "progress_insert_own" on public.player_progress;
create policy "progress_insert_own"
on public.player_progress for insert
with check (auth.uid() = user_id);

drop policy if exists "progress_update_own" on public.player_progress;
create policy "progress_update_own"
on public.player_progress for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "attempts_select_own" on public.attempts;
create policy "attempts_select_own"
on public.attempts for select
using (auth.uid() = user_id);

drop policy if exists "attempts_insert_own" on public.attempts;
create policy "attempts_insert_own"
on public.attempts for insert
with check (auth.uid() = user_id);

insert into public.goblins (name, hp, dungeon)
select * from (
  values
    ('Goblin Scout', 18, 'Sewer'),
    ('Goblin Bruiser', 32, 'Sewer'),
    ('Goblin Shaman', 22, 'Ruins'),
    ('Goblin Captain', 45, 'Ruins')
) as seed(name, hp, dungeon)
where not exists (select 1 from public.goblins);

-- ======================================
-- GAMIFICATION SCHEMA (Modules, Skills, Achievements, Leaderboard)
-- ======================================

-- 1. MODULES (SQL Learning Path) - CREATE & SEED FIRST
create table if not exists public.modules (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  order_index integer not null,
  sql_concept text not null,
  required_level integer not null default 1,
  created_at timestamptz not null default timezone('utc', now())
);

-- Insert SQL concept modules BEFORE challenges
insert into public.modules (name, description, order_index, sql_concept, required_level)
select * from (
  values
    ('SELECT Temelleri', 'Temel SELECT kullanımı', 1, 'SELECT', 1),
    ('WHERE ve Filtreleme', 'WHERE cümlesi ile veri filtreleme', 2, 'WHERE', 1),
    ('ORDER BY ve LIMIT', 'Sıralama ve satır sınırlaması', 3, 'ORDER BY', 2),
    ('GROUP BY ve Aggregates', 'Veri gruplama ve istatistikler', 4, 'GROUP BY', 3),
    ('Advanced Queries', 'Kompleks sorgular ve subqueries', 5, 'ADVANCED', 5)
) as seed(name, description, order_index, sql_concept, required_level)
where not exists (select 1 from public.modules);

-- 2. Update challenges to link to modules
alter table public.challenges add column if not exists module_id bigint references public.modules(id) on delete cascade;
alter table public.challenges add column if not exists order_in_module integer default 0;
alter table public.challenges add column if not exists required_xp integer default 0;

-- NOW insert challenges with module_id references
insert into public.challenges (prompt, difficulty, hint, expected_signature, module_id, order_in_module)
select * from (
  values
    (
      'Goblins tablosundaki en dusuk HP degerine sahip dusmani bul.',
      'easy',
      'ORDER BY hp ASC LIMIT 1 kullanabilirsin.',
      'min-goblin-hp',
      1,
      1
    ),
    (
      'Her zindandaki goblin sayisini listele.',
      'medium',
      'GROUP BY dungeon kullan.',
      'goblin-count-by-dungeon',
      1,
      2
    ),
    (
      'HP degeri 20den buyuk goblinleri HP azalan sirada getir.',
      'hard',
      'WHERE + ORDER BY birlesimi kullan.',
      'high-hp-goblins',
      2,
      1
    )
) as seed(prompt, difficulty, hint, expected_signature, module_id, order_in_module)
where not exists (select 1 from public.challenges);

-- 3. USER PROFILES (Character Data)
create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  level integer not null default 1,
  total_xp integer not null default 0,
  total_damage integer not null default 0,
  total_critical_hits integer not null default 0,
  total_successes integer not null default 0,
  total_attempts integer not null default 0,
  current_combo integer not null default 0,
  best_combo integer not null default 0,
  character_title text,
  last_active timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now())
);

-- 4. USER SKILLS (Skill Tree Tracking)
create table if not exists public.user_skills (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  skill_key text not null,
  unlocked_at timestamptz,
  completed boolean not null default false,
  completed_at timestamptz,
  unique(user_id, skill_key)
);

-- 5. ACHIEVEMENTS
create table if not exists public.achievements (
  id bigint generated by default as identity primary key,
  key text not null unique,
  title text not null,
  description text,
  icon text,
  reward_xp integer not null default 100,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.user_achievements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  achievement_id bigint not null references public.achievements(id) on delete cascade,
  unlocked_at timestamptz not null default timezone('utc', now()),
  unique(user_id, achievement_id)
);

-- 6. MODULE PROGRESS (Track completion per user)
create table if not exists public.user_module_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  module_id bigint not null references public.modules(id) on delete cascade,
  progress_percent integer not null default 0,
  unlocked boolean not null default false,
  completed boolean not null default false,
  completed_at timestamptz,
  last_challenge_id bigint,
  unique(user_id, module_id)
);

-- 7. DAILY CHALLENGES
create table if not exists public.daily_challenges (
  id bigint generated by default as identity primary key,
  challenge_id bigint not null references public.challenges(id) on delete cascade,
  date_active date not null unique,
  reward_multiplier numeric not null default 1.5,
  created_at timestamptz not null default timezone('utc', now())
);

-- 8. USER DAILY ATTEMPTS
create table if not exists public.user_daily_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  daily_challenge_id bigint not null references public.daily_challenges(id) on delete cascade,
  success boolean not null,
  xp_earned integer not null default 0,
  submitted_at timestamptz not null default timezone('utc', now()),
  unique(user_id, daily_challenge_id)
);

-- 9. LEADERBOARD SNAPSHOT (Weekly)
create table if not exists public.leaderboard_snapshot (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  week_start date not null,
  total_xp integer not null,
  rank integer,
  damage_dealt integer not null,
  attempts integer not null,
  success_rate numeric,
  created_at timestamptz not null default timezone('utc', now()),
  unique(user_id, week_start)
);

-- ======================================
-- ROW LEVEL SECURITY
-- ======================================

alter table public.user_profiles enable row level security;
alter table public.user_skills enable row level security;
alter table public.user_achievements enable row level security;
alter table public.user_module_progress enable row level security;
alter table public.user_daily_attempts enable row level security;
alter table public.leaderboard_snapshot enable row level security;

-- User can only see/edit their own profile
drop policy if exists "profiles_select" on public.user_profiles;
create policy "profiles_select"
on public.user_profiles for select
to authenticated
using (true);

drop policy if exists "profiles_update_own" on public.user_profiles;
create policy "profiles_update_own"
on public.user_profiles for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- User can only see/manage their own skills
drop policy if exists "skills_select_own" on public.user_skills;
create policy "skills_select_own"
on public.user_skills for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "skills_insert_own" on public.user_skills;
create policy "skills_insert_own"
on public.user_skills for insert
to authenticated
with check (auth.uid() = user_id);

-- User can only see/manage their own achievements
drop policy if exists "achievements_select_own" on public.user_achievements;
create policy "achievements_select_own"
on public.user_achievements for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "achievements_insert_own" on public.user_achievements;
create policy "achievements_insert_own"
on public.user_achievements for insert
to authenticated
with check (auth.uid() = user_id);

-- User can only see/manage their own module progress
drop policy if exists "module_progress_select_own" on public.user_module_progress;
create policy "module_progress_select_own"
on public.user_module_progress for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "module_progress_insert_own" on public.user_module_progress;
create policy "module_progress_insert_own"
on public.user_module_progress for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "module_progress_update_own" on public.user_module_progress;
create policy "module_progress_update_own"
on public.user_module_progress for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- User can only see/manage their own daily attempts
drop policy if exists "daily_attempts_select_own" on public.user_daily_attempts;
create policy "daily_attempts_select_own"
on public.user_daily_attempts for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "daily_attempts_insert_own" on public.user_daily_attempts;
create policy "daily_attempts_insert_own"
on public.user_daily_attempts for insert
to authenticated
with check (auth.uid() = user_id);

-- ======================================
-- SEED DATA (Additional)
-- ======================================

-- Insert achievements
insert into public.achievements (key, title, description, icon, reward_xp)
select * from (
  values
    ('first_select', 'İlk Seçim', 'İlk SELECT sorgunuzu yazın', '📝', 50),
    ('ten_successes', 'On Başarı', '10 başarılı sorgu çalıştırın', '✅', 150),
    ('first_critical', 'Kritik Vuruş', 'İlk kritik hasar verin', '⚡', 100),
    ('module_completed', 'Modül Tamamlama', 'Bir modülü tamamen tamamlayın', '🎓', 200),
    ('five_day_streak', 'Beş Gün Serisi', '5 gün ard arda oynayın', '🔥', 300),
    ('perfect_accuracy', 'Mükemmel Isabet', 'Bir modülde %100 başarı oranı', '🎯', 500)
) as seed(key, title, description, icon, reward_xp)
where not exists (select 1 from public.achievements where key = seed.key);

-- Insert daily challenges (today and next 6 days)
insert into public.daily_challenges (challenge_id, date_active, reward_multiplier)
select 
  (ARRAY(select id from public.challenges order by random()))[1],
  CURRENT_DATE + day_offset,
  1.5
from (select generate_series(0, 6) as day_offset) s
where not exists (select 1 from public.daily_challenges where date_active = CURRENT_DATE);

-- ======================================
-- Edge Function contract expected by app:
-- name: submit-sql
-- body: { challengeId: number, sql: string }
-- response: { success: boolean, feedback: string, damage: number, critical: boolean, xpAwarded: number }
