-- SQL RPG bootstrap for Supabase Postgres
-- Run in Supabase SQL Editor.

create table if not exists public.challenges (
  id bigint generated by default as identity primary key,
  prompt text not null,
  difficulty text not null check (difficulty in ('easy', 'medium', 'hard')),
  hint text,
  expected_signature text not null
);

create table if not exists public.goblins (
  id bigint generated by default as identity primary key,
  name text not null,
  hp integer not null check (hp > 0),
  dungeon text not null
);

create table if not exists public.player_progress (
  user_id uuid primary key references auth.users(id) on delete cascade,
  level integer not null default 1,
  xp integer not null default 0,
  gold integer not null default 0,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  challenge_id bigint not null references public.challenges(id) on delete cascade,
  sql_text text not null,
  success boolean not null,
  feedback text not null,
  damage integer not null default 0,
  critical boolean not null default false,
  xp_awarded integer not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

create or replace function public.execute_arena_sql(query_text text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  payload jsonb;
begin
  if query_text is null or btrim(query_text) = '' then
    raise exception 'Query bos olamaz';
  end if;

  if query_text ~ ';' then
    raise exception 'Noktali virgul yasak';
  end if;

  if query_text !~* 'select' then
    raise exception 'Sadece SELECT sorgusu kabul edilir';
  end if;

  if query_text ~* '\m(insert|update|delete|drop|alter|create|grant|revoke|truncate)\M' then
    raise exception 'Yazma veya DDL komutlari yasak';
  end if;

  perform set_config('statement_timeout', '3000', true);

  execute format('select coalesce(jsonb_agg(row_to_json(t)), ''[]''::jsonb) from (%s) t', query_text)
  into payload;

  return coalesce(payload, '[]'::jsonb);
end;
$$;

revoke all on function public.execute_arena_sql(text) from public;
grant execute on function public.execute_arena_sql(text) to anon, authenticated;

alter table public.player_progress enable row level security;
alter table public.attempts enable row level security;

drop policy if exists "progress_select_own" on public.player_progress;
create policy "progress_select_own"
on public.player_progress for select
using (auth.uid() = user_id);

drop policy if exists "progress_insert_own" on public.player_progress;
create policy "progress_insert_own"
on public.player_progress for insert
with check (auth.uid() = user_id);

drop policy if exists "progress_update_own" on public.player_progress;
create policy "progress_update_own"
on public.player_progress for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "attempts_select_own" on public.attempts;
create policy "attempts_select_own"
on public.attempts for select
using (auth.uid() = user_id);

drop policy if exists "attempts_insert_own" on public.attempts;
create policy "attempts_insert_own"
on public.attempts for insert
with check (auth.uid() = user_id);

insert into public.goblins (name, hp, dungeon)
select * from (
  values
    ('Goblin Scout', 18, 'Sewer'),
    ('Goblin Bruiser', 32, 'Sewer'),
    ('Goblin Shaman', 22, 'Ruins'),
    ('Goblin Captain', 45, 'Ruins')
) as seed(name, hp, dungeon)
where not exists (select 1 from public.goblins);

-- ======================================
-- GAMIFICATION SCHEMA (Modules, Skills, Achievements, Leaderboard)
-- ======================================

-- 1. MODULES (SQL Learning Path) - CREATE & SEED FIRST
create table if not exists public.modules (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  order_index integer not null,
  sql_concept text not null,
  required_level integer not null default 1,
  created_at timestamptz not null default timezone('utc', now())
);

-- Insert SQL concept modules BEFORE challenges
insert into public.modules (name, description, order_index, sql_concept, required_level)
select * from (
  values
    ('SELECT Temelleri', 'Temel SELECT kullanımı', 1, 'SELECT', 1),
    ('WHERE ve Filtreleme', 'WHERE cümlesi ile veri filtreleme', 2, 'WHERE', 1),
    ('ORDER BY ve LIMIT', 'Sıralama ve satır sınırlaması', 3, 'ORDER BY', 2),
    ('GROUP BY ve Aggregates', 'Veri gruplama ve istatistikler', 4, 'GROUP BY', 3),
    ('Advanced Queries', 'Kompleks sorgular ve subqueries', 5, 'ADVANCED', 5)
) as seed(name, description, order_index, sql_concept, required_level);

-- 2. Update challenges to link to modules
alter table public.challenges add column if not exists module_id bigint references public.modules(id) on delete cascade;
alter table public.challenges add column if not exists order_in_module integer default 0;
alter table public.challenges add column if not exists required_xp integer default 0;

-- NOW insert challenges with module_id references
insert into public.challenges (prompt, difficulty, hint, expected_signature, module_id, order_in_module)
select * from (
  values
    -- MODULE 1: SELECT Temelleri (10 soru)
    ('Tüm goblins tablosunu tam olarak getir.', 'easy', 'SELECT * kullan', 'select-all-goblins', 1, 1),
    ('Goblins tablosundaki tüm name sutunlarini getir.', 'easy', 'SELECT name FROM goblins', 'select-all-names', 1, 2),
    ('Goblins tablosundaki tüm hp degerlerini getir.', 'easy', 'SELECT hp FROM goblins', 'select-all-hp', 1, 3),
    ('Goblins tablosundaki tüm dungeon bilgilerini getir.', 'easy', 'SELECT dungeon FROM goblins', 'select-all-dungeons', 1, 4),
    ('Ilk goblin ve onun tüm bilgilerini getir.', 'easy', 'LIMIT 1 kullan', 'select-first-goblin', 1, 5),
    ('Goblins tablosundan numaralari ve isimlerini getir.', 'easy', 'SELECT id, name FROM goblins', 'select-id-names', 1, 6),
    ('Goblins tablosundan isim ve HP degerlerini getir.', 'easy', 'SELECT name, hp FROM goblins', 'select-names-hp', 1, 7),
    ('Goblins tablosundan HP ve dungeon bilgilerini getir.', 'easy', 'SELECT hp, dungeon FROM goblins', 'select-hp-dungeon', 1, 8),
    ('Ilk iki goblini getir.', 'easy', 'LIMIT 2 kullan', 'select-first-two', 1, 9),
    ('Goblins tablosundan 3 satir getir.', 'easy', 'LIMIT 3 kullan', 'select-first-three', 1, 10),

    -- MODULE 2: WHERE ve Filtreleme (10 soru)
    ('Sewer dungeon bolgesindeki goblins getir.', 'easy', 'WHERE dungeon = ''Sewer'' kullan', 'where-sewer-goblins', 2, 1),
    ('Ruins dungeon bolgesindeki goblins getir.', 'easy', 'WHERE dungeon = ''Ruins'' kullan', 'where-ruins-goblins', 2, 2),
    ('HP degeri 20 den büyük goblins getir.', 'easy', 'WHERE hp > 20 kullan', 'where-high-hp', 2, 3),
    ('HP degeri 30 dan küçük goblins getir.', 'easy', 'WHERE hp < 30 kullan', 'where-low-hp', 2, 4),
    ('HP degeri tam olarak 22 olan goblini getir.', 'easy', 'WHERE hp = 22 kullan', 'where-exact-hp', 2, 5),
    ('Sewer bolgesinde ve HP si 20 den büyük goblins getir.', 'medium', 'WHERE ile iki kosul birlesltir', 'where-sewer-high-hp', 2, 6),
    ('Ismi Scout iceren goblini getir.', 'easy', 'LIKE operatörü kullan', 'where-scout-name', 2, 7),
    ('HP degeri 30 dan fazla goblins isimlerini getir.', 'medium', 'SELECT name ile WHERE birlesltir', 'where-high-hp-names', 2, 8),
    ('Sewer bolgesindeki tüm goblins isim ve HP getir.', 'medium', 'SELECT name, hp + WHERE kombinasyonu', 'where-sewer-details', 2, 9),
    ('HP degeri 20 ile 35 arasinda goblins getir.', 'medium', 'BETWEEN operatörü veya WHERE hp >= 20 AND hp <= 35', 'where-hp-range', 2, 10),

    -- MODULE 3: ORDER BY ve LIMIT (10 soru)
    ('Goblins adi gorre alfabetik siraya getir.', 'easy', 'ORDER BY name ASC kullan', 'order-by-name-asc', 3, 1),
    ('Goblins adi gorre tersten alfabetik siraya getir.', 'easy', 'ORDER BY name DESC kullan', 'order-by-name-desc', 3, 2),
    ('Goblins HP gorre artan siraya getir.', 'easy', 'ORDER BY hp ASC kullan', 'order-by-hp-asc', 3, 3),
    ('Goblins HP gorre azalan siraya getir.', 'easy', 'ORDER BY hp DESC kullan', 'order-by-hp-desc', 3, 4),
    ('En düsük HP sahip goblini getir.', 'easy', 'ORDER BY hp ASC + LIMIT 1', 'order-lowest-hp', 3, 5),
    ('En yüksek HP sahip goblini getir.', 'easy', 'ORDER BY hp DESC + LIMIT 1', 'order-highest-hp', 3, 6),
    ('Ilk 2 goblini ada gorre sirala.', 'medium', 'ORDER BY + LIMIT 2', 'order-first-two-by-name', 3, 7),
    ('Sewer goblinlerini HP gorre azalan siraya getir.', 'medium', 'WHERE + ORDER BY kombinasyonu', 'order-sewer-by-hp-desc', 3, 8),
    ('HP gorre siralanmis ilk 3 goblini getir.', 'medium', 'ORDER BY hp DESC + LIMIT 3', 'order-top-3-hp', 3, 9),
    ('Ada gorre siralanmis son 2 goblini getir.', 'medium', 'ORDER BY DESC + LIMIT 2', 'order-last-2-by-name', 3, 10),

    -- MODULE 4: GROUP BY ve Aggregates (10 soru)
    ('Her dungeon da kac goblin var', 'medium', 'GROUP BY dungeon + COUNT(*)', 'group-count-by-dungeon', 4, 1),
    ('Her dungeon daki goblins in toplam HP sini hesapla.', 'medium', 'GROUP BY dungeon + SUM(hp)', 'group-sum-hp-by-dungeon', 4, 2),
    ('Her dungeon daki goblins in ortalama HP sini hesapla.', 'medium', 'GROUP BY dungeon + AVG(hp)', 'group-avg-hp-by-dungeon', 4, 3),
    ('Tüm goblins in toplam HP sini hesapla.', 'medium', 'SUM(hp) without GROUP BY', 'group-total-hp', 4, 4),
    ('Ortalama goblin HP si nedir', 'medium', 'AVG(hp) kullan', 'group-avg-hp', 4, 5),
    ('En yüksek HP ve en düsük HP yi getir.', 'medium', 'MAX(hp) + MIN(hp)', 'group-max-min-hp', 4, 6),
    ('Her dungeon un ismi ve goblin sayisini getir.', 'medium', 'GROUP BY dungeon + COUNT(*) ayrintili', 'group-dungeon-count-detailed', 4, 7),
    ('Dungeon a gorre toplam HP ve ortalama HP yi getir.', 'hard', 'GROUP BY + SUM + AVG kombinasyonu', 'group-stats-by-dungeon', 4, 8),
    ('20 dan fazla ortalama HP ye sahip dungeon lari getir.', 'hard', 'HAVING kosulu ekle', 'group-having-avg-hp', 4, 9),
    ('En cok goblin i olan dungeon nedir', 'hard', 'GROUP BY + ORDER BY DESC + LIMIT 1', 'group-max-goblins-dungeon', 4, 10),

    -- MODULE 5: Advanced Queries (10 soru)
    ('Sewer dungeon undaki goblins isim ve HP gorre sirali getir.', 'hard', 'WHERE + ORDER BY kombinasyonu', 'advanced-sewer-sorted', 5, 1),
    ('En yüksek HP li 2 goblin in isimlerini getir.', 'hard', 'ORDER BY DESC + LIMIT 2', 'advanced-top-2-strongest', 5, 2),
    ('Her dungeon da en yüksek HP ye sahip goblini bul.', 'hard', 'Subquery veya MAX(hp)', 'advanced-max-per-dungeon', 5, 3),
    ('Ismi A harfi ile baslayan goblins getir.', 'medium', 'LIKE ''A%'' kullan', 'advanced-names-start-with-a', 5, 4),
    ('30 dan fazla HP si olan goblins dungeon a gorre grupla ve say.', 'hard', 'WHERE + GROUP BY + COUNT', 'advanced-high-hp-grouped', 5, 5),
    ('Tüm goblins in HP ortalaması üzerinde goblins getir.', 'hard', 'Subquery + AVG kombinasyonu', 'advanced-above-avg-hp', 5, 6),
    ('Dungeon basina maximum goblin sayisi kactir', 'hard', 'GROUP BY + COUNT + MAX', 'advanced-max-per-dungeon-count', 5, 7),
    ('Ruins dungeon unda en düsük HP li goblin nedir', 'hard', 'WHERE + ORDER BY ASC + LIMIT 1', 'advanced-ruins-weakest', 5, 8),
    ('Her dungeon daki goblins in sayisi ve ortalama güçlerini göster.', 'hard', 'GROUP BY + COUNT + AVG detayli', 'advanced-dungeon-stats', 5, 9),
    ('HP gorre siralanmis tüm goblins in ilk 3 ünü adlari ile getir.', 'hard', 'ORDER BY + LIMIT + SELECT name', 'advanced-top-3-by-hp', 5, 10)
) as seed(prompt, difficulty, hint, expected_signature, module_id, order_in_module);

-- 3. USER PROFILES (Character Data)
create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  level integer not null default 1,
  total_xp integer not null default 0,
  total_damage integer not null default 0,
  total_critical_hits integer not null default 0,
  total_successes integer not null default 0,
  total_attempts integer not null default 0,
  current_combo integer not null default 0,
  best_combo integer not null default 0,
  character_title text,
  last_active timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now())
);

-- 4. USER SKILLS (Skill Tree Tracking)
create table if not exists public.user_skills (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  skill_key text not null,
  unlocked_at timestamptz,
  completed boolean not null default false,
  completed_at timestamptz,
  unique(user_id, skill_key)
);

-- 5. ACHIEVEMENTS
create table if not exists public.achievements (
  id bigint generated by default as identity primary key,
  key text not null unique,
  title text not null,
  description text,
  icon text,
  reward_xp integer not null default 100,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.user_achievements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  achievement_id bigint not null references public.achievements(id) on delete cascade,
  unlocked_at timestamptz not null default timezone('utc', now()),
  unique(user_id, achievement_id)
);

-- 6. MODULE PROGRESS (Track completion per user)
create table if not exists public.user_module_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  module_id bigint not null references public.modules(id) on delete cascade,
  progress_percent integer not null default 0,
  unlocked boolean not null default false,
  completed boolean not null default false,
  completed_at timestamptz,
  last_challenge_id bigint,
  unique(user_id, module_id)
);

-- 7. DAILY CHALLENGES
create table if not exists public.daily_challenges (
  id bigint generated by default as identity primary key,
  challenge_id bigint not null references public.challenges(id) on delete cascade,
  date_active date not null unique,
  reward_multiplier numeric not null default 1.5,
  created_at timestamptz not null default timezone('utc', now())
);

-- 8. USER DAILY ATTEMPTS
create table if not exists public.user_daily_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  daily_challenge_id bigint not null references public.daily_challenges(id) on delete cascade,
  success boolean not null,
  xp_earned integer not null default 0,
  submitted_at timestamptz not null default timezone('utc', now()),
  unique(user_id, daily_challenge_id)
);

-- 9. LEADERBOARD SNAPSHOT (Weekly)
create table if not exists public.leaderboard_snapshot (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  week_start date not null,
  total_xp integer not null,
  rank integer,
  damage_dealt integer not null,
  attempts integer not null,
  success_rate numeric,
  created_at timestamptz not null default timezone('utc', now()),
  unique(user_id, week_start)
);

-- ======================================
-- ROW LEVEL SECURITY
-- ======================================

alter table public.user_profiles enable row level security;
alter table public.user_skills enable row level security;
alter table public.user_achievements enable row level security;
alter table public.user_module_progress enable row level security;
alter table public.user_daily_attempts enable row level security;
alter table public.leaderboard_snapshot enable row level security;

-- User can only see/edit their own profile
drop policy if exists "profiles_select" on public.user_profiles;
create policy "profiles_select"
on public.user_profiles for select
to authenticated
using (true);

drop policy if exists "profiles_update_own" on public.user_profiles;
create policy "profiles_update_own"
on public.user_profiles for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- User can only see/manage their own skills
drop policy if exists "skills_select_own" on public.user_skills;
create policy "skills_select_own"
on public.user_skills for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "skills_insert_own" on public.user_skills;
create policy "skills_insert_own"
on public.user_skills for insert
to authenticated
with check (auth.uid() = user_id);

-- User can only see/manage their own achievements
drop policy if exists "achievements_select_own" on public.user_achievements;
create policy "achievements_select_own"
on public.user_achievements for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "achievements_insert_own" on public.user_achievements;
create policy "achievements_insert_own"
on public.user_achievements for insert
to authenticated
with check (auth.uid() = user_id);

-- User can only see/manage their own module progress
drop policy if exists "module_progress_select_own" on public.user_module_progress;
create policy "module_progress_select_own"
on public.user_module_progress for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "module_progress_insert_own" on public.user_module_progress;
create policy "module_progress_insert_own"
on public.user_module_progress for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "module_progress_update_own" on public.user_module_progress;
create policy "module_progress_update_own"
on public.user_module_progress for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- User can only see/manage their own daily attempts
drop policy if exists "daily_attempts_select_own" on public.user_daily_attempts;
create policy "daily_attempts_select_own"
on public.user_daily_attempts for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "daily_attempts_insert_own" on public.user_daily_attempts;
create policy "daily_attempts_insert_own"
on public.user_daily_attempts for insert
to authenticated
with check (auth.uid() = user_id);

-- ======================================
-- SEED DATA (Additional)
-- ======================================

-- Insert achievements
insert into public.achievements (key, title, description, icon, reward_xp)
select * from (
  values
    ('first_select', 'İlk Seçim', 'İlk SELECT sorgunuzu yazın', '📝', 50),
    ('ten_successes', 'On Başarı', '10 başarılı sorgu çalıştırın', '✅', 150),
    ('first_critical', 'Kritik Vuruş', 'İlk kritik hasar verin', '⚡', 100),
    ('module_completed', 'Modül Tamamlama', 'Bir modülü tamamen tamamlayın', '🎓', 200),
    ('five_day_streak', 'Beş Gün Serisi', '5 gün ard arda oynayın', '🔥', 300),
    ('perfect_accuracy', 'Mükemmel Isabet', 'Bir modülde %100 başarı oranı', '🎯', 500)
) as seed(key, title, description, icon, reward_xp)
where not exists (select 1 from public.achievements where key = seed.key);

-- Insert daily challenges (today and next 6 days)
insert into public.daily_challenges (challenge_id, date_active, reward_multiplier)
select 
  (ARRAY(select id from public.challenges order by random()))[1],
  CURRENT_DATE + day_offset,
  1.5
from (select generate_series(0, 6) as day_offset) s
where not exists (select 1 from public.daily_challenges where date_active = CURRENT_DATE);

-- ======================================
-- Edge Function contract expected by app:
-- name: submit-sql
-- body: { challengeId: number, sql: string }
-- response: { success: boolean, feedback: string, damage: number, critical: boolean, xpAwarded: number }

-- ======================================
-- NESTJS BACKEND TABLES (Database Class Evaluation)
-- ======================================

create table if not exists public.arena_questions (
  id bigint generated by default as identity primary key,
  title text not null,
  prompt text not null,
  correct_answer text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.user_scores (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  question_id bigint references public.arena_questions(id) on delete cascade,
  is_correct boolean not null,
  points integer not null default 0,
  time_spent integer not null default 0,
  score integer,
  arena_id text,
  created_at timestamptz not null default timezone('utc', now())
);

-- Enable Row Level Security for NestJS Tables
alter table public.arena_questions enable row level security;
alter table public.user_scores enable row level security;

-- Policies for NestJS Tables
drop policy if exists "arena_questions_select_all" on public.arena_questions;
create policy "arena_questions_select_all"
on public.arena_questions for select
to authenticated, anon
using (true);

drop policy if exists "user_scores_select_own" on public.user_scores;
create policy "user_scores_select_own"
on public.user_scores for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "user_scores_insert_own" on public.user_scores;
create policy "user_scores_insert_own"
on public.user_scores for insert
to authenticated, anon
with check (true);

-- Seed Data for NestJS Tables
insert into public.arena_questions (title, prompt, correct_answer)
select * from (
  values
    ('Tüm Goblins Sorgusu', 'Goblins tablosundaki tüm satırları ve sütunları getir.', 'SELECT * FROM goblins'),
    ('Güçlü Goblins Filtresi', 'HP değeri 20''den büyük olan tüm goblinleri seç.', 'SELECT * FROM goblins WHERE hp > 20'),
    ('Sewer Dungeon Arayışı', 'Sewer zindanındaki goblinlerin isimlerini getir.', 'SELECT name FROM goblins WHERE dungeon = ''Sewer''')
) as seed(title, prompt, correct_answer)
where not exists (select 1 from public.arena_questions where title = seed.title);
